version: 2.1
executors:
  python:
    docker:
      - image: python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli
jobs:
  check-app:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip && pip install -r requirements.txt

            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: test
          command: |
            . venv/bin/activate
            make test
      - run:
          name: lint
          command: |
            . venv/bin/activate
            make lint
  create-infrastructure:
    executor: aws
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            yum install -y tar gzip curl

            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            chmod +x kubectl
            mkdir -p ~/.local/bin/kubectl
            mv ./kubectl ~/.local/bin/kubectl
            echo "kubectl version"
            kubectl version --short --client

            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
            echo "eksctl version"
            eksctl version
      - run:
          name: create an EKS (Kubernetes) cluster
          command: |
            eksctl create cluster --name recommendation-engine-api
            kubectl get nodes
      - run:
          name: create an IAM role
          command: |
            aws iam create-role \
              --role-name FlaskDeployCBKubectlRole \
              --assume-role-policy-document file://trust.json \
              --output text --query 'Role.Arn'
            aws iam put-role-policy \
              --role-name FlaskDeployCBKubectlRole \
              --policy-name eks-describe \
              --policy-document file://iam-role-policy.json

            kubectl get -n kube-system configmap/aws-auth -o yaml > /tmp/aws-auth-patch.yml
            cat /System/Volumes/Data/private/tmp/aws-auth-patch.yml
workflows:
  default:
    jobs:
      - create-infrastructure
      # - check-app
      # - create-infrastructure:
      #     requires: [check-app]